name: Build and Deploy to Dev Branch

on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Install Dependencies and Build
              run: |
                  npm install
                  npm run build
            - name: Push to Dev Branch
              uses: ad-m/github-push-action@master
              with:
                  branch: gh-pages
                  directory: dist/
                  github_token: ${{ secrets.GITHUB_TOKEN }}
